version: "3"

volumes:
  volume-postgres:

services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - volume-postgres:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: labo
        POSTGRES_PASSWORD: password
        POSTGRES_DB: labo_06
  cache:
    image: memcached:1.5-alpine
    ports:
      - 11211:11211
